# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.cache/wt [current_project]
set_property parent.project_path /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.srcs/sources_1/new/Pulse_Generator.vhd
  /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.srcs/sources_1/new/Clock_Generator.vhd
  /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.srcs/sources_1/new/Task3.vhd
  /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.srcs/sources_1/new/Range_Sensor.vhd
  /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.srcs/sources_1/new/Factor58_Divider.vhd
  /home/linuxlabb/Range_Sensor_Basys3/Range_Sensor_Basys3.srcs/sources_1/new/Echo_Analyser.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/linuxlabb/Range_Sensor_Basys3/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/linuxlabb/Range_Sensor_Basys3/Basys3_Master.xdc]


synth_design -top Range_Sensor -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Range_Sensor.dcp

catch { report_utilization -file Range_Sensor_utilization_synth.rpt -pb Range_Sensor_utilization_synth.pb }
