# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0.xci
# IP: The module: 'zsys_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0.xci
# IP: The module: 'zsys_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/ZynqBerry/te0726-zynqberrydemo1-vivado_2017.1-build_03_20170705132546/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
